### ISSUE TITLE
Tephigram

### ISSUE THREAD

**Issue by andrewgryan** [MetOffice/forest#101]
# Tephigram

- A widget to draw [tephigram](https://en.wikipedia.org/wiki/Tephigram) contours and atmospheric profiles
- Computation should be performed by existing thermodynamic Python packages

**Comment by CarolineBain** [comment]
I'm also wondering if there is anything already started on this elsewhere @bjlittle? Looks like you and @rhattersley did something back in 2014? https://pypi.org/project/tephi/

**Comment by bjlittle** [comment]
@CarolineBain Yup, guilty as charge. My intent back then was to create a de-facto package for tephi plotting.

I've got a branch that ports it to Python3, using perceptual image hashing for graphical tests, and there are also some feature development branches that I've not pushed containing lots of tephi capability e.g., calculating normand points, fog points, hodographs for wind shear etc :stuck_out_tongue_winking_eye:

**Comment by andrewgryan** [comment]
@bjlittle That's fantastic!

**Comment by bjlittle** [comment]
@andrewgryan It's certainly a good starting point, and I've been looking for an excuse to blow the dust off the [tephi](https://github.com/SciTools/tephi) package.

Way back when, I also presented tephi at AMS2015 in a joint cartopy/tephi poster session at the conference, see [here](https://github.com/bjlittle/ams2015/blob/master/posters/cartopy-tephi/cartopy_tephi.png).

**Comment by CarolineBain** [comment]
So awesome :) this is the kind of functionality that would be really exciting for forecasters using the data, especially if it has the capability to use any model data. Have you seen roaming profiles before @bjlittle? One OpMet told me it revolutionised his life when they came available - it's basically a tephigram that dynamically changes depending on location as your mouse clicks down and moves around a map plot. I've only seen it with pre-made plots before, might be challenging to do it on the fly?

**Comment by andrewgryan** [comment]
@CarolineBain I'm thinking a Bokeh implementation of roaming profiles would by best implemented by a `CustomJS` callback responding to `bokeh.events`, e.g. `PanStart`, `PanEnd`, that selects a portion of a `ColumnDataSource`. @bjlittle's thermodynamic and coordinate plotting code would be unaware of how the underlying **source** is populated so in theory roaming could be implemented quite easily at a later date
