### ISSUE TITLE
RDT Visualisation

### ISSUE THREAD

**Issue by claretandy** [MetOffice/forest#120]
There are lots more things we can visualise in FOREST from the RDT output. These include:
- Level 0 and Level 1 polygons of convective cells
- Historical trajectory of the convective cell
- Movement speed and direction of the convective cell
- Colour maps of cloud type and convective phase (see http://www.nwcsaf.org/ct2)
- Human readable labels in the tool-tip

**Comment by andrewgryan** [comment]
This should be fairly easy to introduce to the existing code base. We already have most of the data sitting in the GeoJSON files it's a matter of adding glyphs and load functions to return the correctly formatted data for the MultiLine glyph. Also, adding categorical color mapping for convective types would be neat!

**Comment by CarolineBain** [comment]
Other versions of RDT that I've seen also have the contours getting thicker when you mouse over the polygons (nice!). Plus higher resolution polygons would be good and look more professional too

**Comment by andrewgryan** [comment]
@claretandy it is a good idea to ensure our improvements are backwards compatibility with the augmented JSON you've created and the existing files sitting on AWS

**Comment by andrewgryan** [comment]
Bug spotted in how `file_system` locators combine `args.directory` with `group.directory`

**Comment by andrewgryan** [comment]
Need to separate `image` renderers from general renderers to prevent alpha slider custom JS callback complaining, see line 208 of main.py

**Comment by andrewgryan** [comment]
I think it's worth pointing out that the circles and lines for the historical path can use the same ColumnDataSource. Similarly, the dead reckoning "future" path can use another ColumnDataSource

**Comment by andrewgryan** [comment]
@claretandy your visualisations are live on https://forest.informaticslab.co.uk but the upgrade to allow RDT timestamp navigation needs work. I'm happy to patch it quickly now
