### ISSUE TITLE
Vertical profile

### ISSUE THREAD

**Issue by andrewgryan** [MetOffice/forest#123]
A simple point and click extension of the time series widget to do vertical profiles instead of time series. E.g. `values[:, i, j, k]` becomes `values[t, i, j, :]`

**Comment by andrewgryan** [comment]
@CarolineBain this might be a good first issue to tackle as it builds on existing code and is relatively isolated from the rest of the system

**Comment by twsearle** [comment]
Did we do this in #267?

**Comment by andrewgryan** [comment]
@twsearle yes we did. I've not been keeping on top of the issues

**Comment by twsearle** [comment]
No worries, I had some free time so I thought I could maybe find an issue to close for you. And look! I already found one!

**Comment by twsearle** [comment]
Didn't need to write a line!
