### ISSUE TITLE
forest on PyPI

### ISSUE THREAD

**Issue by bjlittle** [MetOffice/forest#127]
Make the `forest` package available to the community on PyPI via `pip`

**Comment by bjlittle** [comment]
This PR should also cater for the unfortunate renaming of `iris` on PyPI as [scitools-iris](https://pypi.org/project/scitools-iris/) :cry: 

We were just too late to the PyPI party and lost the [iris](https://pypi.org/project/iris/) namespace to someone else...

**Comment by bjlittle** [comment]
The [forest](https://pypi.org/project/forest/#description) namespace has been already taken by another project. However, it hasn't been updated since 4 Dec 2012.

I have emailed the developer nate.skulic@gmail.com asking whether their project is retired, and if so, requesting the namespace for our use.

We may have to consider an alternative PyPI name for `forest`.

**Comment by andrewgryan** [comment]
@bjlittle I think **forest-pangeo** is a good choice, I've sent a slack message to the Informatics Lab to make sure we aren't infringing on the [Pangeo](https://pangeo.io/) brand.

**Comment by claretandy** [comment]
Or how about **scitools-forest**? It uses all the same libraries as scitools, and the same license. Also, if we were to use that convention, should it be **pangeo-forest**?

**Comment by andrewgryan** [comment]
Depends on whether we think people are likely to search for the word forest or the word pangeo first when attempting to pip install it

**Comment by andrewgryan** [comment]
Also, if we go down the route of scitools, should we migrate our repo to SciTools/forest?

**Comment by claretandy** [comment]
SciTools is one route for it. I guess it also depends how interested scitools or pangeo are to have it under their umbrellas. This is not something we can decide on here ... it might be good to discuss this at the hackathon.

**Comment by andrewgryan** [comment]
OK the Lab have gotten back to me and have vetoed forest-pangeo, essentially because it would require Pangeo stakeholder approval and also the other pangeo tools don't have pangeo in their package names

**Comment by andrewgryan** [comment]
@claretandy @bjlittle I think **forest-gump** is probably not my finest idea

**Comment by bjlittle** [comment]
Raising this as a discussion point at the Hackathon might be a simple way to canvas devs, users and stakeholders... btw naming things is SO hard sometimes, probably best to have some options to start everyone's creative juices 😁

**Comment by bjlittle** [comment]
@claretandy @andrewgryan @CarolineBain Perhaps it's an option to migrate the repo to under the SciTools organisation? It would still be Met Office owned. 

Maybe worth mulling over or exploring? :thinking:
