### ISSUE TITLE
PEP8 compliance

### ISSUE THREAD

**Issue by bjlittle** [MetOffice/forest#129]
Ensure that the code base is [PEP8](https://www.python.org/dev/peps/pep-0008/) compliant, and enable automated PEP8 checking via a bot for each GitHub PR to maintain compliance e.g., see https://stickler-ci.com/

**Comment by andrewgryan** [comment]
While PEP8 is a nice style-guide, there are aspects of it that encourage code that's less easy to read. Don't get me wrong 90% of PEP8 is great advice that every Python programmer should follow. Can we tailor the stickler-ci to ignore parts of PEP8 that we view as detrimental to readability?

Kelvin Henney has a great talk on readability, it stretches all the way back to how monks and scribes in the middle ages aligned their text to ease readability

**Comment by bjlittle** [comment]
Yup, see https://stickler-ci.com/docs#flake8, you can control `flake8` and opt in to cutom PEP8 compliance, as you see fit.

**Comment by andrewgryan** [comment]
Great! Fill your boots, I look forward to this pull request

**Comment by bjlittle** [comment]
Nice one... kinda busy today, but I'll progress this tomorrow earliest, if that's okay?

**Comment by andrewgryan** [comment]
@bjlittle no worries take your time with it, I'm putting effort into documentation this week so there's no rush to get the code linted

**Comment by bjlittle** [comment]
Cheers, I'll ping you when I've got something... I'm actually experimenting with a different approach that you might like.
