### ISSUE TITLE
Handling of unrecognised "file_type" configuration

### ISSUE THREAD

**Issue by rhattersley** [MetOffice/forest#130]
Provide some sort of fail-fast feedback for invalid "file_type" values.

Currently if the configuration file contains an unsupported value for "file_type" then [data.file_loader()](https://github.com/informatics-lab/forest/blob/87fc2147a608d0b2c768635099eddcc619d03877/forest/data.py#L78) silently returns an implicit `None` for the loader, resulting in a later error of:
```
  File ".../forest/forest/view.py", line 19, in render
    self.source.data = self.loader.image(state)
AttributeError: 'NoneType' object has no attribute 'image'

```

**Comment by andrewgryan** [comment]
Agreed, this is a glaring error that could be patched with a unit test checking for an Exception given a invalid `file_type` keyword
