### ISSUE TITLE
Iris uses too much memory for ReadTheDocs

### ISSUE THREAD

**Issue by andrewgryan** [MetOffice/forest#142]
An `environment.yml` file with `iris=2.2.0` as the only dependency resulted in 

<img width="834" alt="Screen Shot 2019-09-29 at 12 28 28" src="https://user-images.githubusercontent.com/22789046/65831710-dfe79e80-e2b4-11e9-8c09-8145a605c13c.png">

**Comment by andrewgryan** [comment]
Using pip install with `scitools-iris` results in a missing dependency for `cartopy` of `GEOS 3.3.3` and `Proj`

**Comment by bjlittle** [comment]
@andrewgryan The `pip` issue with `iris` is most likely indirectly due to an issue with the `cartopy` dependencies. Perhaps check `cartopy` on StackOverflow or the latest chatter on GitHub i.e., [this](https://github.com/SciTools/cartopy/issues/1346) seems relevant

**Comment by bjlittle** [comment]
@andrewgryan Yeah, the dependencies of `iris` is scary big... But other people have had issues with the space provisioned by RTD to build other projects.

As an aside, I'm keen to slim `iris` down to it's core, then users opt into other functionality desperately, which builds on the core - this would solve your problem (most likely)

**Comment by andrewgryan** [comment]
4014a7eea8ee266b7dd5dd9e485c9b54aaf77a2d solves the import issue but might need more guard clauses to protect environments other than ReadTheDocs from running without **iris**

**Comment by andrewgryan** [comment]
Actually, the excessive memory is coming from conda itself during the resolve environment phase. I'm switching back to using pip
