### ISSUE TITLE
Expand public/private naming?

### ISSUE THREAD

**Issue by rhattersley** [MetOffice/forest#153]
[Some](https://github.com/informatics-lab/forest/blob/v0.4.2/forest/data.py#L400) modules/classes use a single leading underscore to denote non-public methods, etc., but [others](https://github.com/informatics-lab/forest/blob/v0.4.2/forest/unified_model.py#L112) [don't](https://github.com/informatics-lab/forest/blob/v0.4.2/forest/db/locate.py#L71).

The underscore pattern can be useful when trying to grok code structure, so do we want to adopt it more widely?

**Comment by rhattersley** [comment]
NB. There are other ways to highlight important interfaces (e.g. [abstract] base classes), but that's getting more heavy-handed which is perhaps overkill at this point!

**Comment by andrewgryan** [comment]
I think good API docs are in order, especially around abstract base classes for certain contracts between components. In recent a recent branch I've tidied up the public/private module level interfaces through a custom `@export` decorator but I agree that classes which are implementing an interface should use a single undescore for methods not directly involved in the primary purpose of the class.

```python
class Foo(AbstractNavigator):
   def variables(self):
          """Publicly available to everyone"""
   ...
   def _parse_arcane_meta_data(self):
         """Probably not wise to depend on this being around in future releases"""
```
