### ISSUE TITLE
Change units from K to C when you display temperature

### ISSUE THREAD

**Issue by CarolineBain** [MetOffice/forest#168]
On mouse over the units will be displayed in the tool tip. When the variable is temperature there is a conversion in the code so that it displays in Celsius rather than Kelvin, but the mouse over tool tip still displays it as 'K'

**Comment by thaohtp** [comment]
Hi @CarolineBain,
I'm aiming to work on [Hacktoberfest](https://hacktoberfest.digitalocean.com/), then I came across this issue. It looks like to me that I just need to change all occurrences of `K` to `C` in [`rdt.py`](https://github.com/informatics-lab/forest/blob/master/forest/rdt.py#L497-L498), right? Can you explain to me more?
