### ISSUE TITLE
Visualise multiple fields from the same model

### ISSUE THREAD

**Issue by rhattersley** [MetOffice/forest#171]
For example:

1. Two different phenomena for the same validity time and from the same model run.
2. The same phenomenon at the same validity time but different model runs.

_Is this something we need to do?_

**Comment by andrewgryan** [comment]
This is definitely needed. It has been touched on by #146 but is expressed in more concrete terms here. I've experimented with [multiple colorbars before](https://github.com/andrewgryan/bokeh-playground/blob/ffe25db2f89b5cb8c7fb9cdb1e4cdfff3a607902/layers/cbar.py#L53)
