### ISSUE TITLE
Fix units and colorscales for CMIP6 data

### ISSUE THREAD

**Issue by stevehadd** [MetOffice/forest#192]
Currently we're just using FOREST defaults and the units as they come in from the catalogue. We may want to review what units and scales we use. For example
* Kelvin or celsius for temp
* mm.h^-1 for precip. This is also average monthly precip currently, so we may need to incorporate this information somewhere.
* wind - km/h, knots m.s^-1 ?

and many others as well

**Comment by andrewgryan** [comment]
@stevehadd does this kind of thing relate to @CarolineBain's issue #168?
