### ISSUE TITLE
Custom piece-wise color palettes

### ISSUE THREAD

**Issue by andrewgryan** [MetOffice/forest#200]
Bokeh accepts a list of strings representing color palettes, e.g. `bokeh.palettes.Accent[3] -> ['#7fc97f', '#beaed4', '#fdc086']`

The idea is to provide a pure math function to take a list of intervals, e.g. `[0, 1, 5, 8, 10]`, and produce a list of N evenly spaced samples, e.g. `[0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4]` that can generate repeated colors

```python
>>>  intervals = [0, 1, 5, 8, 10]
>>> idx = pure_func(intervals, n=10)
>>> idx
... [0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4]
>>> [bokeh.palettes.Accent[5][i] for i in idx]
... ['#7fc97f', '#beaed4', '#beaed4', '#beaed4', '#beaed4',
...  '#fdc086', '#fdc086', '#fdc086',  '#ffff99', '#ffff99', '#386cb0']
```

https://en.wikipedia.org/wiki/Step_function

**Comment by andrewgryan** [comment]
`f = scipy.interpolate.interp1d(x, y, kind='next')` perhaps?

**Comment by andrewgryan** [comment]
![example-interp1d](https://user-images.githubusercontent.com/22789046/68305797-34462100-00a0-11ea-94d4-c009e1cacaf6.png)

**Comment by afinnen** [comment]
There is a use case for uniform spacing of colours, especially when the user thresholds of interest are "somewhat logarithmic" (but not truely logarithmic), e.g. visibility or precipitation. 

Here is an example of how this is implemented in matplotlib for the London Model visibility colour scale. 

```
def __Visibility(self,item):
        
        bounds = [0,50,100,200,600,1000,2000,5000,10000,20000,30000,50000,100000]        
        hot=plt.get_cmap('hot')
        greens=plt.get_cmap('YlGnBu')
        greenpts=greens(range(0,255,255//7)[1:7])
        number_hotcols=len(bounds)-len(greenpts)-1
        hotpts=np.linspace(0,250,num=number_hotcols)
        hotpts=hot([int(hp) for hp in hotpts])
        viscolors=np.concatenate([hotpts,greenpts])
        cmap,norm=mpl.colors.from_levels_and_colors(bounds,viscolors)
        
        if item=='cmap':
            return cmap
        elif item=='norm':
            return norm
        elif item=='cbar':
            ticks=bounds[1:-1]
            cbar=plt.colorbar(orientation='horizontal',pad=.02,norm=self.norm, boundaries=bounds,ticks=ticks,spacing='uniform')
            cbar.set_label('Visibility in m',fontsize='x-small')
            return cbar   ```
