### ISSUE TITLE
Move repo to a new organisation?

### ISSUE THREAD

**Issue by rhattersley** [MetOffice/forest#201]
Is it time to move this repo to a new GitHub organisation?

For example, I'd like to install the Stickler-CI app as a step along the way for #129, but the request to install the app has had to go to the @informatics-lab admins. As I understand it, they're not really involved with this repo any more, so this will just be a distraction for them.

**Comment by rhattersley** [comment]
Unsuprisingly, the name "forest" is already taken... some (currently) available alternatives:

- forest-app
- forest-met / met-forest
- forest-geo / geo-forest

I'm sure you can think of better ones!

**Comment by andrewgryan** [comment]
I'm an Informatics lab admin, but I take your point that we could move organisation. We've migrated most of our infrastructure already

**Comment by andrewgryan** [comment]
@rhattersley after further reading of the GitHub docs this seems to be a low-risk operation. All of the existing forks attempting to push to the old repo will be redirected to the new one. We can advise our collaborators to change their upstream/origins to match the new organisation URL

**Comment by rhattersley** [comment]
Yes - it's less of a technical issue and more of a coming-up-with-a-decent-name issue. :-)

**Comment by andrewgryan** [comment]
@rhattersley I don't think anyone has MetOffice/forest
