### ISSUE TITLE
Incorrect state when switching between multi and single level variables

### ISSUE THREAD

**Issue by stevehadd** [MetOffice/forest#207]
While testing CMIP6 functionality for PR #195, I noticed a bug  in my code. The problem stems from the fact that when switching from a single-level field (e.g. tas - air temperature at surface) to a multi-level field (e.g. ua - easterly wind component), the state variable passed into the image function does not contain any values. This is presumably because it is still using what is selected in the GUI (which is nothing) even though the Navigator class has been called to supply pressures. 
This sort of thing may be sorted by the planned GUI upgrades, so feel free to close this issue or ignore it until afterwards. I have created a work around of displaying a blank image until the user selects a pressure, but I think it would be better for some data to display immediately.

**Comment by andrewgryan** [comment]
@stevehadd Good spot, it is certainly a worthy bug to squash while we anticipate a more full-featured `State` implementation, for example #176

**Comment by andrewgryan** [comment]
@stevehadd I'm currently trying to remove direct access to State in #222, could that refactoring help solve the issue? The idea is that the `Selector` class (to be generalised to multiple specialised selectors) controls things like type checking. Or is this related to how the GUI renders itself, e.g. #219

**Comment by stevehadd** [comment]
> @stevehadd I'm currently trying to remove direct access to State in #222, could that refactoring help solve the issue? The idea is that the `Selector` class (to be generalised to multiple specialised selectors) controls things like type checking. Or is this related to how the GUI renders itself, e.g. #219

I think that this should solve this issue, and I don't think its related to #219. If I've understood you correctly, the Selector class would then take care of things like checking that when the pressures function is called on the Navigator to update that field of the state, the Selector would ensure that the pressure field is consistent with that (i.e. Noen if it is a single level field, a valid selection if pressure levels are supplied). Presumably the GUI would then have both a valid list of pressures in the dropdown, and the correct selection of pressure level based on the state.  Does that description sound consistent with what you're planning for #222 ?

**Comment by andrewgryan** [comment]
@stevehadd I've become less convinced that state parsing should be done by the `render` method. Instead a `stream.map(state_to_props)` which converts a stream of states to a stream of args is a much simpler approach. It also makes `View.render()` state agnostic.
