### ISSUE TITLE
requirements.txt - bokeh 2.0.1 only. 

### ISSUE THREAD

**Issue by wolfiex** [MetOffice/forest#394]
Forest falls over on bokeh `2.0.2` - it does not display anything within serve mode. The requirements file should be `==2.0.1` and not `>=2.0.1` to reflect this until the origin of this is found. 

It is likely a bokeh package error, as the issue persists across other applications.

**Comment by andrewgryan** [comment]
@wolfiex I use 2.0.2 and it works fine, although I haven't installed the latest build of bokeh in a few weeks maybe there's a temporary bug
