### ISSUE TITLE
Update CLI: Using something like Typer

### ISSUE THREAD

**Issue by kaedonkers** [MetOffice/forest#452]
Pull in some learnings from Fores-Lite:
https://github.com/MetOffice/forest-lite/blob/master/forest_lite/cli.py

**Comment by andrewgryan** [comment]
The specific issue we encountered was placement of `--show` prevents the detection of `files` list. Brought about by mixing support for bokeh and forest specific command line arguments.
```
forest file.nc --show # works
forest --show file.nc # broken
```
A minimal fix would be to correct the above situation, perhaps clearly specifying where bokeh arguments go `forest [forest args] -- [bokeh args]` use a bare double minus to separate the namespaces

An elegant solution for long term consideration would be to break functionality into sub-commands e.g. 
`forest view FILE [FILE ...]` and `forest launch config.yaml`

**Comment by andrewgryan** [comment]
#461 closes this issue
