### ISSUE TITLE
Guidance on user defined injecty drivers

### ISSUE THREAD

**Issue by kaedonkers** [MetOffice/forest#457]

**Comment by andrewgryan** [comment]
Another idea for "injecty" drivers is to have drivers implemented as TCP clients. 

The Bokeh app can start a TCP listener socket that lets drivers (TCP clients) connect/disconnect at will. A well defined API to communicate over would be needed. I haven't worked out how custom glyphs would work yet, serializing/deserializing the Bokeh "document" could get expensive if the data is also copied. 

The benefit is the driver code would be completely decoupled from the FOREST machinery. It could even be written in a different language.

**Comment by andrewgryan** [comment]
I've thought about this further and think it fits neatly into the existing driver format

```yaml
datasets:
    - label: 'third party driver'
       driver:
            name: tcp
            settings:
                host: 127.0.0.1
                port: 65432
```

The driver is then any process connecting to `sock.bind(('127.0.0.1', 65432))` and communicating using a protocol we define. Probably, `byte,json header,json body` format so the first byte says how long the header is, the header contains a `content-length` value to indicate how long the body is and then we can use Python libraries like `orjson` to rapidly serialize/deserialize the communication.

Ideally, forest would ship with a base class or decorator to abstract away the socket/message protocol and call methods on the driver with arguments driven by the clicks in the Bokeh server interface.

This way the **contract** between users and forest is well-defined, implement functions that return json serializable data (it'll be going through a websocket anyway so it needs to be serializable)

**Comment by andrewgryan** [comment]
```python
# Third-party script run independently
driver = forest.helpers.TcpDriver()

@driver.navigator.variables
def variables():
       """Custom method to populate variables dropdown menu
          when user selects this dataset"""
       return ["air_temperature"]

def main(host: str, port: int):
    driver.settings(file_names=["hello.nc"])
    driver.listen((host, port))
```

**Comment by andrewgryan** [comment]
The requirement to use a socket like TCP has been made obsolete by RPC drivers. HTTP is a layer above TCP in the stack and will eventually avoid TCP issues when HTTP/3 is adopted as a standard.

A third party Python object-oriented API exists.

```python
class Dataset:
    def navigator() -> Navigator:
    # etc.

class Navigator:
class MapView:
class Profile:
class Series:
```

I'll fully document this approach since I tried and failed to implement a decorator syntax `@driver.navigator.variables` because the current implementation of FOREST is stateful and it's nice to have `__init__()` methods and access to `self` to do anything non-trivial
