### ISSUE TITLE
Update info on setting up  development environment for forest

### ISSUE THREAD

**Issue by stevehadd** [MetOffice/forest#61]
There is not currently much info on the steps recommended for setting up a development environment, This should include the following info:
* what OS to use
* setting up conda with required packages and conda envs
* mounting data in s3 buckets
* running forest locally

**Comment by andrewgryan** [comment]
Hi Steve,

I'm spinning up the software stack today. If there is anything that's not obvious I'll let you know so you can improve the installation/getting started docs.
