### ISSUE TITLE
Rescale colourscales for longer rainfall accumulation periods.

### ISSUE THREAD

**Issue by stevehadd** [MetOffice/forest#64]
Issue #23 has now included rainfall accumulations in the apps. The colour scale is not appropriate for longer accumulation periods and should be scaled based on the length of the period.

**Comment by andrewgryan** [comment]
Would it be better to replace the pre-cooked colorbar images with matplotlib generated colorbars?

**Comment by andrewgryan** [comment]
Created a branch to deal with this issue [forest_64_colorbars](/informatics-lab/forest/tree/forest_64_colorbars)
